### ISSUE TITLE
`404` status page when no found space in space details

### ISSUE THREAD

**Issue by itsalb3rt** [Cowofi/cowofi#21]
@rafieltq for the `404` status page when no found space in space details, you can use the explorer space empty status

![image](https://user-images.githubusercontent.com/35310226/184796055-4c9696b6-4308-4283-a067-a7d79fa56ffa.png)

_Originally posted by @itsalb3rt in https://github.com/Cowofi/cowofi/issues/2#issuecomment-1216121092_

**Comment by rafieltq** [comment]
So i have to do the 404 page with that illustration, right?
