### ISSUE TITLE
Legal terms and policy privacy

### ISSUE THREAD

**Issue by itsalb3rt** [Cowofi/cowofi#31]
**Description**

The app require legal terms and privacy of the data

**Comment by pcabreram1234** [comment]
I have these.

In awating of your response.


Legal terms.

In general the use of this application and the commercialization of it is under the terms of the MIT open source license type, In General we receive and store any information you enter on our Website, through the CoWoFi App. This type of information include only the full name (If the user sees it convenient), his/her email and posible places information in geolocation terms.

### **How You Can Contact Us**

If you have questions about this Privacy Policy, please contact us at: [cowofi@gmail.com](mailto:cowofi@gmail.com)
. Please be aware that calls to and from cowofi may be recorded. We may use the call recordings to monitor our customer service for quality or compliance purposes, to check the accuracy of the information you provide us, for fraud prevention purposes, or to provide training to our staff. We will retain the call recordings for as long as reasonably necessary to perform such activities and then delete them. Any personal information obtained from you during the call will be treated in accordance with the provisions of this Privacy Policy. ©2022 Cowofi Inc. All rights reserved.

# Privacy of data

Within the terms of protection of sensitive information offered by the CoWoFi application, there is the encryption of your access codes as well as the protection of them in fairly reliable cloud servers and above all supported by the Open Source community. Keep in mind that the information that is sent between the chats between the person who rents the space and who is interested in it is under their responsibility the quality of the information they share.
