### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by itsalb3rt** [Cowofi/cowofi#49]
**Is your feature request related to a problem? Please describe.**
Update dependencies to a compatible version using yarn upgrade-interactive

Make a sure you test before solved it.

**Comment by vinmaster** [comment]
Hi, I've made a PR here: https://github.com/Cowofi/cowofi/pull/51

**Comment by itsalb3rt** [comment]
Hello @vinmaster Thanks 😀  , I check it right now.

**Comment by itsalb3rt** [comment]
Is done with the PR #51
