### ISSUE TITLE
Social network share buttons

### ISSUE THREAD

**Issue by pcabreram1234** [Cowofi/cowofi#50]
**Description**

Added the possibility to share spaces in social networks.

![Image](https://user-images.githubusercontent.com/35310226/184998043-2a135ccb-d251-461c-a9fb-44e30f001e2b.png)

A button in the top-right of the spaces

**Comment by pcabreram1234** [comment]
I am currently working in this, I just made the UI Design.

**Comment by itsalb3rt** [comment]
Sure! go ahead!

**Comment by pcabreram1234** [comment]
I just made the required.

On the right top of the spaces I added a button.
When the user click it will trigger a dialog window with the two social media buttons (Facebook and Twitter)

I built it with the [vue-social-sharing](https://github.com/nicolasbeauvais/vue-social-sharing).

### Files Modified

- .quasar/app.js
- src/pages/Spaces/CompleteDetails.vue 

### Component built

- ShareButton.vue

**Comment by itsalb3rt** [comment]
solved in #52
