### ISSUE TITLE
Space between items on footer is wrong

### ISSUE THREAD

**Issue by itsalb3rt** [Cowofi/cowofi#57]
**Description**

The items on the footer of the page have different space size, in the image below you can see the difference of the left and the right

![image](https://user-images.githubusercontent.com/35310226/211944261-5857b989-ea5a-455c-aa59-04e3eea0e970.png)

**Comment by missaelcv** [comment]
Saludos, Creo que tomare esta parte para realizarla

**Comment by missaelcv** [comment]
![prueba](https://user-images.githubusercontent.com/58403931/212182324-caa5e0c6-9ae8-4736-be58-28fe51a47f71.png)

**Comment by itsalb3rt** [comment]
Solved #58
